version: "3"
networks:
  dspacenet:
services:
  db:
    container_name: dspace_db_${PROJECT_NAME}
    image: postgres:9.5-alpine
    environment:
      POSTGRES_DB: "dspace_${PROJECT_NAME}"
      POSTGRES_USER: dspace
      POSTGRES_PASSWORD: dspace
    volumes:
      - /var/lib/postgresql/data
    networks:
      dspacenet:
      
  dspace:
    container_name: dspace_${PROJECT_NAME}
    image: dspace:dspace_${PROJECT_NAME}_latest
    build:
      context: ./
      dockerfile: Dockerfile.sedici
    command: start
    environment:
      CATALINA_OPTS: "-Xmx1024m -Xms512m -XX:MaxPermSize=256m"
      DSPACE_GIT_URL: "${DSPACE_GIT_URL}"
      DSPACE_GIT_REVISION: "${DSPACE_GIT_REVISION}"
      DSPACE_WEBAPPS: "${DSPACE_WEBAPPS}" # posible values: "jspui xmlui  mirage2 rest oai rdf sword swordv2"
      DSPACE_ROOT_WEBAPP: "${DSPACE_ROOT_WEBAPP}"
      POSTGRES_DB_HOST: "dspace_db_${PROJECT_NAME}"
      POSTGRES_DB_NAME: "dspace_${PROJECT_NAME}"
      DSPACE_USER: dspace
      DSPACE_PASS: dspace
    networks:
      dspacenet:
    volumes:
      - ../:/dspace/
      - ~/.m2/:/dspace/.m2/
    ports:
      - "9090:8080"
    depends_on: 
      - db