version: "3.7"
networks:
  default:
    name: ${DOCKER_EXTERNAL_NETWORK_NAME}
services:
  dspacedb:
    image: postgres:9.5-alpine
    environment:
      POSTGRES_DB: "dspace"
      POSTGRES_USER: dspace
      POSTGRES_PASSWORD: dspace
    volumes:
      - /var/lib/postgresql/data 
  dspace:
    image: dspace:dspace_${COMPOSE_PROJECT_NAME}_latest
    build:
      context: ./
      dockerfile: Dockerfile.sedici
    command: start
    environment:
      CATALINA_OPTS: "-Xmx1024m -Xms512m -XX:MaxPermSize=256m"
      DSPACE_WEBAPPS: "${DSPACE_WEBAPPS}" # posible values: "jspui xmlui  mirage2 rest oai rdf sword swordv2"
      DSPACE_WEBAPPS: "${DSPACE_WEBAPPS}" # posible values: "mirage2 rest oai rdf sword swordv2"
      DSPACE_ROOT_WEBAPP: "${DSPACE_ROOT_WEBAPP}"
      POSTGRES_DB_HOST: "dspacedb"
      POSTGRES_DB_NAME: "dspace"
      DSPACE_USER: dspace
    volumes:
      - ../:/dspace/
      - ~/.m2/:/dspace/.m2/
    ports:
      - "8080:8080"
    depends_on: 
      - dspacedb
  dspacesolr:
    image: dspace/dspace-solr
    ports:
    - published: 8983
      target: 8983
    stdin_open: true
    tty: true
    volumes:
    - solr_authority:/opt/solr/server/solr/authority/data
    - solr_oai:/opt/solr/server/solr/oai/data
    - solr_search:/opt/solr/server/solr/search/data
    - solr_statistics:/opt/solr/server/solr/statistics/data
volumes:
  assetstore:
  solr_authority:
  solr_oai:
  solr_search:
  solr_statistics:
