version: '2'
volumes:
  artifactory: {}
services:
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:5.9.0
    container_name: artifactory
    ports:
     - 8081:8081
    volumes:
      - artifactory:/var/opt/jfrog/artifactory
#    Add extra Java options by uncommenting the following lines
#    environment:
#     - EXTRA_JAVA_OPTIONS=-Xmx4g
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
  dspace:
    depends_on: 
      - artifactory